### ISSUE TITLE
`entrypoint` PyPI package name

### ISSUE THREAD

**Issue by nekitdev** [ponty/entrypoint2#11]
I've been working on a small project that aims at providing a simple way to define *entry points*, called [`entrypoint.py`](https://github.com/nekitdev/entrypoint.py).

```python
from entrypoint import entrypoint

@entrypoint(__name__)
def main() -> None:
    print("Hello, world!")
```

`entrypoint.py` intentionally does not use black magic (like frames), aiming to be as simplistic as possible.

I was wondering if I could use `entrypoint` name for my package on PyPI, which @ponty is a maintainer of.

**Comment by ponty** [comment]
I'm not the author of `entrypoint` package, I was added as a maintainer, but I don't want to work on it, I work on the `entrypoint2` package, see  #1

You can find the author of `entrypoint` package on Pypi page and in #1.

I will not delete other people's work on PYPI.

Why don't you choose a different package name?

**Comment by nekitdev** [comment]
Sorry, I might've expressed myself poorly. `entrypoint`'s owner wanted to make sure you don't have any concerns regarding me acquiring the package on PyPI.

**Comment by ponty** [comment]
OK it is clear now. You can use it as you want. I only work on `entrypoint2`, which was forked from `entrypoint` long time ago.
Please remove me from the maintainers' list.

**Comment by nekitdev** [comment]
I see, thanks!
