### ISSUE TITLE
Remove redundant "argparse" requirement

### ISSUE THREAD

**Issue by abhiTronix** [ponty/entrypoint2#9]
As of Python >= 2.7 and >= 3.2, the [`argparse`](https://docs.python.org/3/howto/argparse.html) module is maintained within the Python standard library. Please remove this redundant requirement from entrypoint2 as it is creating unnecessary package conflict. Thank you.

**Comment by ponty** [comment]
Thanks. I fixed it recently in b1fe388f889e6fbb55b999fba907b869019c5a88 but forgot to push it.

**Comment by abhiTronix** [comment]
@ponty Thanks, but can you push this release to pypi as soon as possible?

**Comment by ponty** [comment]
Done.

**Comment by abhiTronix** [comment]
@ponty Thanks a lot.
